#!/bin/sh

# Args to this test script are passed to e2sync, suggestions are :
#   --debug
#   --verbose

set -e

done_fs() {
  # Allow umount to fail
  sudo umount $1 2>/dev/null || true
}
init_fs() {
  mkdir -p $1
  done_fs $1  # Handle leftover from a previously failed test
  dd if=/dev/zero of=$1.img bs=1M count=1 status=none
  mke2fs -q $1.img
  sudo mount -o loop $1.img $1
  sudo chown $(id -u) $1
}
do_fs() {
  # debugfs is noisy, it always prints its name and version; we filter
  # its output and thus we have to explictly handle its error (cannot
  # test LHS of pipe with POSIX shell)
  err=$(debugfs -w -R "$*" $1 2>&1 |grep -v ^"debugfs 1")
  if [ -n "$err" ]; then
    echo "$err"
    exit 2
  fi
}

teardown() {
  done_fs t/a
  done_fs t/b
  rm -rf t
}
trap teardown 0 INT QUIT

create() {
  # Create a file with a somewhat varying content
  date +%s.%N >$1
}

# Generate as much differences as possible : file and folder presence, attr,
# extended attr, ACLs, and so on. Also plant traps like hard links.
init_fs t/a
init_fs t/b
create t/a/to-copy
mkdir  t/a/src
create t/a/src/new
create t/b/to-delete
mkdir  t/b/dst
create t/b/dst/old
create t/a/const
ln     t/a/const t/a/const-hl
cp -p  t/a/const t/b
chmod 0600 t/a/const
sudo chown root t/a/const
setfacl -m user:root:rw t/a
setfacl -m group:root:x t/b/const

# Run our magic sync
sudo ./e2sync t/a t/b "$@"

# Then make sure they look the same from all points of view

# Meta (attributes)
(cd t/a && sudo \ls -lRn .) >t/a.ls
(cd t/b && sudo \ls -lRn .) >t/b.ls
diff t/a.ls t/b.ls

# Data
(cd t/a && sudo find . -type f -exec md5sum '{}' ';') |sort >t/a.data
(cd t/b && sudo find . -type f -exec md5sum '{}' ';') |sort >t/b.data
diff t/a.data t/b.data

# Meta (extended attributes)
(cd t/a && sudo lsattr -R .) |sort >t/a.attr
(cd t/b && sudo lsattr -R .) |sort >t/b.attr
diff t/a.attr t/b.attr

# Meta (ACLs)
(cd t/a && sudo getfacl -RPt .) |sort >t/a.acl
(cd t/b && sudo getfacl -RPt .) |sort >t/b.acl
diff t/a.acl t/b.acl

# Hardlinks
if [ $(stat -c %i t/b/const) != $(stat -c %i t/b/const-hl) ]; then
  echo "hard link not preserved"
  exit 1
fi
